[project]
name = 'Decentralized-Cleaning-Services-Quality-Assurance-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.customer-feedback]
path = 'contracts/customer-feedback.clar'
clarity_version = 2
epoch = 2.5

[contracts.inspection-coordination]
path = 'contracts/inspection-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
